In [13]:
import pandas as pd

In [14]:
'''df = pd.read_excel('/home/costela/Documentos/Escorpiao_pesa/Quadro2/dados/base_preliminar.xlsx')
ministerio = pd.read_csv('/home/costela/Documentos/Escorpiao_pesa/Quadro2/dados/pesa_ministerio_site.csv', sep=';')'''

df = pd.read_excel('/home/usuario/Documentos/Lucas/Projetos estudos/Escorpiao_pesa/Quadro2/dados/base_preliminar.xlsx')
ministerio = pd.read_csv('/home/usuario/Documentos/Lucas/Projetos estudos/Escorpiao_pesa/Quadro2/dados/pesa_ministerio_site.csv', sep=';')

In [15]:
# Filtra somente os pesas comm SAESc
ministerio = ministerio[ministerio['ATENDIMENTOS'].str.contains('escorp', case=False, na=False)].copy()

In [16]:
# Normaliza o texto a coluna MUNICIPIO
from unidecode import unidecode   # Importa função que remove acentos e caracteres Unicode

ministerio['MUNICIPIO'] = (               # Sobrescreve a coluna 'municipio' com o texto padronizado
   ministerio['MUNICIPIO']
   .astype(str)    # Converte todos os valores para texto (string)
                                 # Evita erro caso existam números, NaN etc.
   .apply(unidecode)             # Remove acentos e caracteres especiais Unicode
                                 # Ex: "São João" -> "Sao Joao"
   .str.upper()                  # Transforma todo o texto em CAIXA ALTA
                                 # Ex: "Sao Joao" -> "SAO JOAO"
                     # Indica que o padrão é uma expressão regular
   ) .str.strip()               # Remove espaços no início e fim do texto, Ex: " SAO JOAO " -> "SAO JOAO"

'''.str.replace(r'[^A-Z0-9\s]',  # Expressão regular:
                                 # [^ ... ] = tudo que NÃO estiver dentro
                                 # A-Z = letras maiúsculas
                                 # 0-9 = números
                                 # \s = espaços
                                 # Portanto remove pontuação, hífen, vírgula etc.
    '',                         # Substitui os caracteres encontrados por vazio, Ou seja, remove
    regex=True'''

".str.replace(r'[^A-Z0-9\\s]',  # Expressão regular:\n                                 # [^ ... ] = tudo que NÃO estiver dentro\n                                 # A-Z = letras maiúsculas\n                                 # 0-9 = números\n                                 # \\s = espaços\n                                 # Portanto remove pontuação, hífen, vírgula etc.\n    '',                         # Substitui os caracteres encontrados por vazio, Ou seja, remove\n    regex=True"

In [17]:
# Contagem do número de PESA por municipio 
n_pesa = ministerio['MUNICIPIO'].value_counts(dropna=False).reset_index()
n_pesa.columns = ['PESA_SITE', 'N_PESA']

In [18]:
# Merge do numero de PESA (contagem de Pesa) ao df

df = df.merge(
    n_pesa,
    left_on="MUNI_REFERENCIADO",
    right_on="PESA_SITE",
    how="left"
)
df

,Unnamed: 0,ACESSO_LOCAL,MULTIPLO_PESA,REGIAO,PESA,MUNI_REFERENCIADO,OBSERVACOES,LAT_MUNI,LON_MUNI,LAT_PESA,...,MG_ORIGINAL,LEVE_10,MG_10,LEVE_11A59,MG_11A59,LEVE_60,MG_60,TOTAL_AMPOLAS,PESA_SITE,N_PESA
0,0,0,0,ARACATUBA,PENAPOLIS,ALTO ALEGRE,TODOS,-21.582059,-50.166198,-21.416404,...,11,11,5,159,1,109,3,23,NaN,NaN
1,1,0,0,ARACATUBA,PENAPOLIS,AVANHANDAVA,TODOS,-21.460333,-49.946516,-21.416404,...,16,12,5,166,11,49,1,36,NaN,NaN
2,2,0,0,ARACATUBA,PENAPOLIS,BARBOSA,TODOS,-21.265661,-49.951816,-21.416404,...,14,40,8,309,2,91,0,38,NaN,NaN
3,3,0,0,ARACATUBA,VALPARAISO,BENTO DE ABREU,TODOS,-21.271572,-50.811723,-21.230655,...,3,8,1,57,1,14,2,21,NaN,NaN
4,4,0,0,ARACATUBA,CLEMENTINA,BILAC,TODOS,-21.403962,-50.474640,-21.556698,...,13,15,2,155,3,77,3,41,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
640,640,0,0,SAO JOSE DO RIO PRETO,SAO JOSE DO RIO PRETO,IPIGUA,TODOS,0.000000,0.000000,0.000000,...,22,16,5,153,10,60,2,36,NaN,NaN
641,641,0,0,SAO JOSE DO RIO PRETO,SAO JOSE DO RIO PRETO,ONDA VERDE,TODOS,0.000000,0.000000,0.000000,...,16,35,3,165,5,40,1,9,NaN,NaN
642,642,1,0,PIRACICABA,PIRACICABA,PIRACICABA,TODOS,0.000000,0.000000,0.000000,...,171,688,81,5926,46,1209,16,452,PIRACICABA,2.0
643,643,0,0,PIRACICABA,PIRACICABA,RIO DAS PEDRAS,TODOS,0.000000,0.000000,0.000000,...,14,40,4,210,0,36,1,19,NaN,NaN
644,644,1,0,CARAGUATATUBA,ILHABELA,ILHABELA,TODOS,0.000000,0.000000,0.000000,...,0,0,0,5,0,1,0,0,ILHABELA,1.0

In [19]:
# As duas listas que você quer atribuir
lista_pesa_site = ['FERRAZ DE VASCONCELOS','MIRANTE DO PARANAPANEMA','PARAGUACU PAULISTA','PRESIDENTE EPITACIO',
'SANTA CRUZ DO RIO PARDO','SANTA RITA DO PASSA QUATRO','SAO JOAQUIM DA BARRA','SAO JOSE DO BARREIRO',
'SAO JOSE DO RIO PARDO','SAO LUIS DO PARAITINGA']

lista_n_pesa = [1,1,1,1,1,1,1,1,1,1,1,1]

# Filtro de municípios
filtro = df['MUNI_REFERENCIADO'].isin([
    'FERRAZ DE VASCONCELOS', 'MIRANTE DO PARANAPANEMA', 'PARAGUACU PAULISTA', 
    'PRESIDENTE EPITACIO', 'SANTA CRUZ DO RIO PARDO', 'SANTA RITA DO PASSA QUATRO', 
    'SAO JOAQUIM DA BARRA', 'SAO JOSE DO BARREIRO', 'SAO JOSE DO RIO PARDO', 
    'SAO LUIS DO PARAITINGA'])

# Atribuição simultânea zipando as duas listas
df.loc[filtro, ['PESA_SITE', 'N_PESA']] = list(zip(lista_pesa_site, lista_n_pesa))

In [20]:
# Corrige numero de PESA de SAO JOSE DO RIO PRETO
df.loc[df['PESA_SITE']=='SAO JOSE DO RIO PRETO', 'N_PESA'] = 5

In [21]:
# Preenche os nomes de todos os municipios em PESA SITE. Todos que possuem N_PESA >0 são PESA
df['PESA_SITE'] = df['MUNI_REFERENCIADO']

In [25]:
# Substitui os NAs da coluna diretamente no DataFrame
df['N_PESA'] = df['N_PESA'].fillna(0)

In [22]:
# Verifica quais PESA contidos na lista do Ministerio não migraram pelo merge para o DF
# n_pesa[~n_pesa['PESA_SITE'].isin(df['PESA_SITE'])]

In [23]:
# Compara se o numero de PESA da lista do Ministerio esta batendo com a do DF
display(df['N_PESA'].sum(),
n_pesa['N_PESA'].sum())

np.float64(242.0)

np.int64(242)

In [26]:
df

,Unnamed: 0,ACESSO_LOCAL,MULTIPLO_PESA,REGIAO,PESA,MUNI_REFERENCIADO,OBSERVACOES,LAT_MUNI,LON_MUNI,LAT_PESA,...,MG_ORIGINAL,LEVE_10,MG_10,LEVE_11A59,MG_11A59,LEVE_60,MG_60,TOTAL_AMPOLAS,PESA_SITE,N_PESA
0,0,0,0,ARACATUBA,PENAPOLIS,ALTO ALEGRE,TODOS,-21.582059,-50.166198,-21.416404,...,11,11,5,159,1,109,3,23,ALTO ALEGRE,0.0
1,1,0,0,ARACATUBA,PENAPOLIS,AVANHANDAVA,TODOS,-21.460333,-49.946516,-21.416404,...,16,12,5,166,11,49,1,36,AVANHANDAVA,0.0
2,2,0,0,ARACATUBA,PENAPOLIS,BARBOSA,TODOS,-21.265661,-49.951816,-21.416404,...,14,40,8,309,2,91,0,38,BARBOSA,0.0
3,3,0,0,ARACATUBA,VALPARAISO,BENTO DE ABREU,TODOS,-21.271572,-50.811723,-21.230655,...,3,8,1,57,1,14,2,21,BENTO DE ABREU,0.0
4,4,0,0,ARACATUBA,CLEMENTINA,BILAC,TODOS,-21.403962,-50.474640,-21.556698,...,13,15,2,155,3,77,3,41,BILAC,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
640,640,0,0,SAO JOSE DO RIO PRETO,SAO JOSE DO RIO PRETO,IPIGUA,TODOS,0.000000,0.000000,0.000000,...,22,16,5,153,10,60,2,36,IPIGUA,0.0
641,641,0,0,SAO JOSE DO RIO PRETO,SAO JOSE DO RIO PRETO,ONDA VERDE,TODOS,0.000000,0.000000,0.000000,...,16,35,3,165,5,40,1,9,ONDA VERDE,0.0
642,642,1,0,PIRACICABA,PIRACICABA,PIRACICABA,TODOS,0.000000,0.000000,0.000000,...,171,688,81,5926,46,1209,16,452,PIRACICABA,2.0
643,643,0,0,PIRACICABA,PIRACICABA,RIO DAS PEDRAS,TODOS,0.000000,0.000000,0.000000,...,14,40,4,210,0,36,1,19,RIO DAS PEDRAS,0.0
644,644,1,0,CARAGUATATUBA,ILHABELA,ILHABELA,TODOS,0.000000,0.000000,0.000000,...,0,0,0,5,0,1,0,0,ILHABELA,1.0